name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'modulo2/**'
  pull_request:
    branches:
      - master
    paths:
      - 'modulo2/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: modulo2
        run: python -m pip install --upgrade pip && pip install pytest
        
      - name: Run tests
        working-directory: modulo2
        run: python -m pytest